#!/bin/sh -e

ALFRESCO_SCRIPT="{{ alfresco_user_home }}/bin/alfresco.sh"

if [ "$1" = "start" ]; then
 su - {{ alfresco_user }} "${ALFRESCO_SCRIPT}" "start"
elif [ "$1" = "stop" ]; then
 su - {{ alfresco_user }} "${ALFRESCO_SCRIPT}" "stop"
elif [ "$1" = "restart" ]; then
 su - {{ alfresco_user }} "${ALFRESCO_SCRIPT}" "stop"
 su - {{ alfresco_user}} "${ALFRESCO_SCRIPT}" "start"
else
 echo "Usage: /etc/init.d/alfresco [start|stop|restart]"
fi
